# Local Configuration

key_path: local_key.pem

token:
  issuer: http://localhost:8080/auth
  issuer_grpc: localhost:8081
  audience: localhost
  expiration: 300 # (3600 = 1 hour, 300 = 5 minutes)
  expiration_refresh: 86400 # 1 day
