name: Build and Deploy Docker image to Cloud Run

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Install buf
        run: |
          BIN="/usr/local/bin" && \
          VERSION="1.45.0" && \
          curl -sSL \
          "https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-$(uname -s)-$(uname -m)" \
          -o "${BIN}/buf" && \
          chmod +x "${BIN}/buf"

      - name: Generate
        run: make proto

      - name: Build
        run: go build ./cmd/auth
